const Erros = {
    USUARIO_JA_EXISTE: "USUARIO_JA_EXISTE",
    EMAIL_MAL_FORMADO: "EMAIL_MAL_FORMADO",
    SENHA_FRACA: "SENHA_FRACA",
    USUARIO_NAO_EXISTE: "USUARIO_NAO_EXISTE",
    SENHA_INVALIDA: "SENHA_INVALIDA",
    ACESSO_NEGADO: "ACESSO_NEGADO"
} as const

export default Erros