services:

  postgres:
    image: postgres:16-alpine
    container_name: pg-server
    environment:
      - POSTGRES_DB=arq_hex
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - 5432:5432
    